overwrite: true
schema: "https://graphql.anilist.co/"
generates:
  app/generated/anilist-graphql.ts:
    documents: "app/**/*.{ts,tsx}"
    plugins:
      - "typescript"
      - "typescript-operations"
    config:
      declarationKind: "type"
      maybeValue: T | undefined
      useTypeImports: true
