overwrite: true
schema: "https://graphql.anilist.co/"
documents: "app/**/*.{ts,tsx,gql}"
generates:
  app/modules/anilist/graphql.ts:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typed-document-node"
    config:
      declarationKind: "type"
      maybeValue: T | undefined
      useTypeImports: true
